CREATE TABLE users(
  id SERIAL PRIMARY KEY,
  "firstName" VARCHAR(200) NOT NULL,
  "lastName" VARCHAR(200) NOT NULL,
  username VARCHAR(50) NOT NULL UNIQUE,
  password_digest VARCHAR(255) NOT NULL
);